#include "d2_costmap_obstacle_merger/costmap_obstacle_merger_node.hpp"
#include "rclcpp_components/register_node_macro.hpp"

RCLCPP_COMPONENTS_REGISTER_NODE(d2::costmap_obstacle_merger::CostMapObstacleMergerNode)